@php

$knazske_a_muzske_reholne_povolania_z_Detvy = [

    [
        "meno_a_tituly"         => "Andrej Biely",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => "05.03.1692",
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Ján Krnáč",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "1682",
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "22.05.1716",
        "miesto_umrtia"         => "Horná Ždaňa",
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Matej Czimra",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "20.04.1755",
        "miesto_umrtia"         => "Žarnovica",
        "miesto_pochovania"     => "Horné Hámre",
    ],

    [
        "meno_a_tituly"         => "Matúš Michna",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "1693/1694",
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "14.02.1769",
        "miesto_umrtia"         => "Očová",
        "miesto_pochovania"     => "Očová",
    ],

    [
        "meno_a_tituly"         => "Andrej Matussek SJ",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "člen Spoločnosti Ježišovej (jezuiti)",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "27.11.1703",
        "miesto_narodenia"      => "Detva",
        "datum_ordinovania"     => "1731",
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => null,
        "miesto_umrtia"         => "1753",
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Matej Hakkel",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "24.09.1730",
        "miesto_narodenia"      => "Detva",
        "datum_ordinovania"     => "1752",
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "06.12.1769",
        "miesto_umrtia"         => "Veľká (Zvolenská) Slatina",
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Maurus Pavel Pataky OSB",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "člen Rádu svätého Benedikta (benediktíni)",
        "datum_obliecky_vstupu" => "obliečka mníšskeho rúcha 06.08.1911",
        "datum_prve_sluby"      => "25.05.1913",
        "datum_dozivotne_sluby" => "28.05.1916",
        "datum_narodenia"       => "05.04.1893",
        "miesto_narodenia"      => "Detva",
        "datum_ordinovania"     => "29.06.1916",
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "30.11.1965",
        "miesto_umrtia"         => "Bratislava",
        "miesto_pochovania"     => "Komárno",
    ],

    [
        "meno_a_tituly"         => "Jozef Goljan",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "25.02.1904",
        "miesto_narodenia"      => "Detva",
        "datum_ordinovania"     => "28.01.1934",
        "miesto_ordinovania"    => "Spišská Kapitula",
        "datum_umrtia"          => "15.04.1941",
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => "Detva, dolný cintorín",
    ],

    [
        "meno_a_tituly"         => "Longín Imrich Gáborík CCG",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "člen Kongregácie bratov tešiteľov z Getsemani",
        "datum_obliecky_vstupu" => "vstup do kongregácie 02.02.1928",
        "datum_prve_sluby"      => "02.03.1929",
        "datum_dozivotne_sluby" => "28.08.1932",
        "datum_narodenia"       => "13.08.1911",
        "miesto_narodenia"      => "Detva-Kriváň",
        "datum_ordinovania"     => "05.07.1935",
        "miesto_ordinovania"    => "Brno, Česká republika",
        "datum_umrtia"          => "05.09.1977",
        "miesto_umrtia"         => "Chatham, Kanada",
        "miesto_pochovania"     => "Chatham, Kanada-Ontário",
    ],

    [
        "meno_a_tituly"         => "Michal Hukel",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "25.02.1912",
        "miesto_narodenia"      => "Hriňová-Krivec II.",
        "datum_ordinovania"     => "27.01.1935",
        "miesto_ordinovania"    => "Banská Bystrica",
        "datum_umrtia"          => "17.06.1991",
        "miesto_umrtia"         => "Veľký Biel",
        "miesto_pochovania"     => "Kriváň, cintorín",
    ],

    [
        "meno_a_tituly"         => "Tomáš Imrich Ďurica OP",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "člen Rehole kazateľov (dominikáni)",
        "datum_obliecky_vstupu" => "vstup do rehole v r. 1991",
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "07.10.1915",
        "miesto_narodenia"      => "Detva",
        "datum_ordinovania"     => "29.06.1939",
        "miesto_ordinovania"    => "Bratislava",
        "datum_umrtia"          => "12.09.1992",
        "miesto_umrtia"         => "Dunajská Lužná",
        "miesto_pochovania"     => "Dunajská Lužná, cintorín",
    ],

    [
        "meno_a_tituly"         => "Emil Prokop SVD",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "člen Spoločnosti Božieho slova (verbisti)",
        "datum_obliecky_vstupu" => "vstup do spoločnosti v r. 1941",
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "22.07.1922",
        "miesto_narodenia"      => "Detva-Kriváň",
        "datum_ordinovania"     => "05.07.1967",
        "miesto_ordinovania"    => "Magdeburg, Nemecko",
        "datum_umrtia"          => "29.10.2006",
        "miesto_umrtia"         => "Nitra",
        "miesto_pochovania"     => "Nitra",
    ],

    [
        "meno_a_tituly"         => "Ján Buzák",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => "17.06.1984",
        "miesto_ordinovania"    => "Banská Bystrica",
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Jozef Strapko",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => "15.06.1986",
        "miesto_ordinovania"    => "Banská Bystrica",
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Martin Sebíň",
        "obrazok"               => null,
        "poznamka"              => "štúdium dokončil za farnosť Hriňová",
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => "13.06.1987",
        "miesto_ordinovania"    => "Banská Bystrica",
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Pavel Vilhan",
        "obrazok"               => null,
        "poznamka"              => "štúdium dokončil za farnosť Kriváň",
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => "31.07.1999",
        "miesto_ordinovania"    => "Banská Bystrica",
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Andrej Valent OCD",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "člen Rádu bosých karmelitánov",
        "datum_obliecky_vstupu" => "vstup do rádu v r. 1998",
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => "10.09.2005",
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => "13.05.2006",
        "miesto_ordinovania"    => "Krakov, Poľsko",
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Andrej Porubský",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => "21.09.2008",
        "miesto_ordinovania"    => "Banská Bystrica",
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Pavel Cerovský",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => "20.06.2009",
        "miesto_ordinovania"    => "Banská Bystrica",
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Peter Sekereš",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => "20.06.2009",
        "miesto_ordinovania"    => "Banská Bystrica",
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Florián Štefan Kamenský OFM",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "člen Rádu menších bratov františkánov",
        "datum_obliecky_vstupu" => "vstup do rádu v r. 2005",
        "datum_prve_sluby"      => "11.08.2007",
        "datum_dozivotne_sluby" => "13.09.2013",
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Peter Lupták",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => "09.06.2012",
        "miesto_ordinovania"    => "Banská Bystrica",
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Jozef Golian",
        "obrazok"               => null,
        "poznamka"              => "ženatý trvalý diakon v Mníchovsko-Freisingskej arcidiecéze v Nemecku",
        "clen_radu_nazov"       => null,
        "datum_obliecky_vstupu" => "vysv. 06.10.2018  Mníchov, Nemecko",
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],
];

$zenske_reholne_povolania_z_Detvy = [
    [
        "meno_a_tituly"         => "Agáta Elena Kuricová CSC",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "členka Kongregácie sestier Tešiteliek Božského Srdca Ježišovho (tešiteľky)",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "18.04.1910",
        "miesto_narodenia"      => "Detva",
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "21.01.1996",
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => "Rajhrad, Česká republika",
    ],

    [
        "meno_a_tituly"         => "Štefánia Elena Sekerešová CSC",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "členka Kongregácie sestier Tešiteliek Božského Srdca Ježišovho (tešiteľky)",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => "v r. 1933",
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "28.06.1910",
        "miesto_narodenia"      => "Detva-Piešť",
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "01.11.1986",
        "miesto_umrtia"         => "Jiřetín pod Jedlovou, Česká republika",
        "miesto_pochovania"     => "Jiřetín pod Jedlovou, Česká republika",
    ],

    [
        "meno_a_tituly"         => "Alžbeta Elena Hulinová CSC",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "členka Kongregácie sestier Tešiteliek Božského Srdca Ježišovho (tešiteľky)",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => "v r. 1932",
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "28.03.1913",
        "miesto_narodenia"      => "Detva-Piešť",
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "12.01.2002",
        "miesto_umrtia"         => "Bratislava",
        "miesto_pochovania"     => "Bratislava-Vrakuňa",
    ],

    [
        "meno_a_tituly"         => "Laurencia Emília Kuricová CSC",
        "obrazok"               => null,
        "poznamka"              => "rodná sestra tešiteľky Agáty Eleny Kuricovej",
        "clen_radu_nazov"       => "členka Kongregácie sestier Tešiteliek Božského Srdca Ježišovho (tešiteľky)",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "10.11.1913",
        "miesto_narodenia"      => "Detva",
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "1943",
        "miesto_umrtia"         => "Rajhrad, Česká republika",
        "miesto_pochovania"     => "Rajhrad, Česká republika",
    ],

    [
        "meno_a_tituly"         => "Kristína Amália Gáboríková CSC",
        "obrazok"               => null,
        "poznamka"              => "rodná sestra rehoľného kňaza Longína Imricha Gáboríka",
        "clen_radu_nazov"       => "členka Kongregácie sestier Tešiteliek Božského Srdca Ježišovho (tešiteľky)",
        "datum_obliecky_vstupu" => "vstup do kongregácie 26.10.1934",
        "datum_prve_sluby"      => "14.06.1937",
        "datum_dozivotne_sluby" => "v r. 1943",
        "datum_narodenia"       => "30.11.1918",
        "miesto_narodenia"      => "Detva-Kriváň",
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "08.04.2006",
        "miesto_umrtia"         => "Bratislava",
        "miesto_pochovania"     => "Bratislava-Vrakuňa",
    ],

    [
        "meno_a_tituly"         => "Vincencia Mária Sekerešová CSC",
        "obrazok"               => null,
        "poznamka"              => "rodná sestra tešiteľky Štefánie Eleny Sekerešovej",
        "clen_radu_nazov"       => "členka Kongregácie sestier Tešiteliek Božského Srdca Ježišovho (tešiteľky)",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "14.12.1920",
        "miesto_narodenia"      => "Detva-Piešť",
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "04.11.2001",
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => "Rajhrad, Česká republika",
    ],

    [
        "meno_a_tituly"         => "Ivana Mária Kulichová DKL",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "členka Kongregácie Dcér kresťanskej lásky (vincentky)",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "19.10.1924",
        "miesto_narodenia"      => "Detva-Skliarovo",
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "07.11.1997",
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => "Močenok",
    ],

    [
        "meno_a_tituly"         => "Klára Mária Luptáková S.Praem.",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "členka Kongregácie sestier premonštrátok",
        "datum_obliecky_vstupu" => "vstup do kongregácie 31.08.1946, obliečka rehoľného rúcha 15.08.1948",
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => "01.09.1957",
        "datum_narodenia"       => "22.10.1925",
        "miesto_narodenia"      => "Detva-Zlatno",
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "21.10.2013",
        "miesto_umrtia"         => "Vrbové",
        "miesto_pochovania"     => "Vrbové",
    ],

    [
        "meno_a_tituly"         => "Nonna Margita Budáčová DKL",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "členka Kongregácie Dcér kresťanskej lásky (vincentky)",
        "datum_obliecky_vstupu" => "vstup do kongregácie 09.06.1947",
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "10.02.1926",
        "miesto_narodenia"      => "Detva-Piešť",
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "1956",
        "miesto_umrtia"         => "Jasov",
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Rufina Mária Fekiačová CSC",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "najskôr členka Kongregácie Dcér kresťanskej lásky (vincentky), neskôr členka Kongregácie sestier Tešiteliek Božského Srdca Ježišovho (tešiteľky)",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => "08.09.1927",
        "datum_ordinovania"     => "Detva",
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "26.06.2006",
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Bibiána Magdaléna Sekerešová DKL",
        "obrazok"               => null,
        "poznamka"              => "rodná sestra tešiteliek Štefánie Eleny a Vincencie Márie",
        "clen_radu_nazov"       => "členka Kongregácie Dcér kresťanskej lásky (vincentky)",
        "datum_obliecky_vstupu" => "vstup do kongregácie 06.09.1948",
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => "19.06.1930",
        "datum_ordinovania"     => "Detva-Piešť",
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "07.10.2017",
        "miesto_umrtia"         => "Mendryka, Česká republika",
        "miesto_pochovania"     => "Svitavy, Česká republika",
    ],

    [
        "meno_a_tituly"         => "Elena Fekiačová IKV",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "členka Sekulárneho inštitútu Krista Veľkňaza",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => "09.10.1930",
        "miesto_narodenia"      => "Čakanovce",
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => "26.11.2003",
        "miesto_umrtia"         => "Zvolen",
        "miesto_pochovania"     => "Detva",
    ],

    [
        "meno_a_tituly"         => "Helena Stehlíková SCSC",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "členka Kongregácie milosrdných sestier Svätého kríža",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Tarzícia Ľudmila Bagová SSpS.",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "členka Misijnej kongregácie služobníc Ducha Svätého",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => "06.02.1994",
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Tabita Anna Chlebničanová OSF",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "členka Kongregácie školských sestier sv. Františka Assiského",
        "datum_obliecky_vstupu" => "postulát 10.09.1994; noviciát 12.08.1995",
        "datum_prve_sluby"      => "11.08.1997",
        "datum_dozivotne_sluby" => "16.08.2003",
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Františka Kristína Cerovská S.Praem.",
        "obrazok"               => null,
        "poznamka"              => "rodná sestra kňaza Pavla Cerovského",
        "clen_radu_nazov"       => "členka Kongregácie sestier premonštrátok",
        "datum_obliecky_vstupu" => "vstup do kongregácie 04.01.2003, obliečka rehoľného rúcha 15.08.2003",
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => "13.08.2011",
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],

    [
        "meno_a_tituly"         => "Magdaléna Krnáčiková",
        "obrazok"               => null,
        "poznamka"              => null,
        "clen_radu_nazov"       => "vo formácii pre vstup do Kongregácie sestier karmelitánok Dieťaťa Ježiša",
        "datum_obliecky_vstupu" => null,
        "datum_prve_sluby"      => null,
        "datum_dozivotne_sluby" => null,
        "datum_narodenia"       => null,
        "miesto_narodenia"      => null,
        "datum_ordinovania"     => null,
        "miesto_ordinovania"    => null,
        "datum_umrtia"          => null,
        "miesto_umrtia"         => null,
        "miesto_pochovania"     => null,
    ],
];

@endphp

<x-web.layout.master :pageData="$pageData">

    {{-- Duchovné povolania --}}
    <x-web.page.section name="PAGE: ({{ $pageData->title }}) -" class="static-page pad_b_50">

    </x-web.page.section>

</x-web.layout.master>
