<?php

return [

    'title' => 'Farnosť Detva',
    'title_prefix' => '',
    'title_postfix' => ' | Farnosť Detva',

    'keywords' => 'farnosť, Detva, svadba, krst, oznamy, predmanželská príprava, pohreb',
    'description' => 'Webové stránky farnosťi Detva.',

    'preppend_route_static_pages' => 'frontend.static-pages',

    'title-articles' => [
        'all' => 'Najnovšie články',
        'author' => 'Články autora: ',
        'category' => 'Články z kategórie: ',
        'date' => 'Články z roku: ',
        'tags' => 'Články s kľúčovým slovom: ',
        'search' => 'Články obsahujúce výraz: ',
    ],

    'admin_texts' => [

        'dashboard_title'       => 'Dashboard',
        'dashboard_description' => 'Dashboard',
        'dashboard_header'      => 'Dashboard',

        'testimonials_title'              => 'Svedectvá',
        'testimonials_description'        => 'Administrácia - správa sekcie: Svedectvá',
        'testimonials_description_create' => 'Administrácia - pridanie nového svedectva viery',
        'testimonials_description_edit'   => 'Administrácia - Editácia svedectva',
        'testimonials_header'             => 'Svedectvá viery',
        'testimonials_header_create'      => 'Nové svedectvo viery',
        'testimonials_header_edit'        => 'Úprava svedectva viery',

        'sliders_title'              => 'Myšlienky',
        'sliders_description'        => 'Administrácia - správa sekcie: Slider s myšlienkou',
        'sliders_description_create' => 'Administrácia - pridanie nového Slider-u s myšlienkou',
        'sliders_description_edit'   => 'Administrácia - Editácia slider-u s myšlienkou',
        'sliders_header'             => 'Obrázok s myšlienkou',
        'sliders_header_create'      => 'Nový obrázok s myšlienkou',
        'sliders_header_edit'        => 'Úprava obrázku s myšlienkou',

        'banners_title'              => 'Baner',
        'banners_description'        => 'Administrácia - správa sekcie: Baner',
        'banners_description_create' => 'Administrácia - pridanie nového Baner-u',
        'banners_description_edit'   => 'Administrácia - Editácia Baner-u',
        'banners_header'             => 'Baner',
        'banners_header_create'      => 'Nový baner',
        'banners_header_edit'        => 'Úprava baner-u',

        'tags_title'              => 'Kľúčové slová',
        'tags_description'        => 'Administrácia - správa sekcie: Kľúčové slová',
        'tags_description_create' => 'Administrácia - vytvorenie nového Kľúčového slova (tagu)',
        'tags_description_edit'   => 'Administrácia - Editácia Kľúčového slova (tagu)',
        'tags_header'             => 'Kľúčové slová',
        'tags_header_create'      => 'Nové kľúčové slovo',
        'tags_header_edit'        => 'Úprava kľúčového slova',

        'priests_title'              => 'Kňazi',
        'priests_description'        => 'Administrácia - správa sekcie: Kňazi',
        'priests_description_create' => 'Administrácia - Pridanie nového kňaza',
        'priests_description_edit'   => 'Administrácia - Editácia kňaza',
        'priests_header'             => 'Kňazi našej farnosti',
        'priests_header_create'      => 'Nový duchovný',
        'priests_header_edit'        => 'Duchovný - editovanie',

        'news_title'              => 'Články',
        'news_description'        => 'Administrácia článkov',
        'news_description_create' => 'Administrácia - vytvorenie nového článku',
        'news_description_edit'   => 'Administrácia - Editácia článku',
        'news_header'             => 'Články',
        'news_header_create'      => 'Nový článok',
        'news_header_edit'        => 'Úprava článku',

        'categories_title'              => 'Kategórie článkov',
        'categories_description'        => 'Administrácia - správa sekcie: Kategórie článkov',
        'categories_description_create' => 'Administrácia - Vytvorenie novej kategórie',
        'categories_description_edit'   => 'Administrácia - Editácia Kategórie',
        'categories_header'             => 'Kategórie článkov',
        'categories_header_create'      => 'Nová kategória',
        'categories_header_edit'        => 'Úprava kategórie',

        'permissions_title'              => 'Povolenia',
        'permissions_description'        => 'Administrácia - správa sekcie: Práva prístupu do jednotlivých sekcií.',
        'permissions_description_create' => 'Administrácia - Vytvorenie nového povolenia',
        'permissions_description_edit'   => 'Administrácia - Editácia povolenia',
        'permissions_header'             => 'Povolenia',
        'permissions_header_create'      => 'Nové povolenie',
        'permissions_header_edit'        => 'Úprava povolenia',

        'roles_title'              => 'Roly',
        'roles_description'        => 'Administrácia - správa sekcie: Roly užívateľov.',
        'roles_description_create' => 'Administrácia - Vytvorenie novej roly',
        'roles_description_edit'   => 'Administrácia - Editácia roly',
        'roles_header'             => 'Užívateľské roly',
        'roles_header_create'      => 'Nová rola',
        'roles_header_edit'        => 'Úprava roly',

        'users_title'              => 'Užívatelia',
        'users_description'        => 'Administrácia - správa sekcie: Užívateľ.',
        'users_description_create' => 'Administrácia - Vytvorenie nového užívateľa',
        'users_description_edit'   => 'Administrácia - Editácia užívateľa',
        'users_description_show'   => 'Môžete si pozrieť detailné informácie uživateľa',
        'users_header'             => 'Užívateľ',
        'users_header_create'      => 'Nový užívateľ',
        'users_header_edit'        => 'Úprava užívateľa',
        'users_header_show'        => 'Profil',

        'static-pages_title'              => 'Statické stránky',
        'static-pages_description'        => 'Tu môžete zakladať nové stránky a ich mediálny obsah',
        'static-pages_description_create' => 'Vytvorenie novej statickej stránky',
        'static-pages_description_edit'   => 'Editácia statickej stránky',
        'static-pages_header'             => 'Statické stránky',
        'static-pages_header_create'      => 'Nová statická stránka',
        'static-pages_header_edit'        => 'Úprava statickej stránky',

        'files_title'              => 'Súbory',
        'files_description'        => 'Sem môžete vkladať rôzne súbory na statické stránky',
        'files_description_create' => 'Pridanie ďalšieho súboru',
        'files_description_edit'   => 'Zmena súboru alebo jeho vlastností',
        'files_header'             => 'Súbory',
        'files_header_create'      => 'Vložiť súbor',
        'files_header_edit'        => 'Upraviť súbor',

        'file-types_title'              => 'Typy súborov',
        'file-types_description'        => 'Kategorizácia súborov',
        'file-types_description_create' => 'Vytvorenie novej kategórie pre súbory',
        'file-types_description_edit'   => 'Zmena údajov v kategórii pre súbory',
        'file-types_header'             => 'Typy vkladaných súborov',
        'file-types_header_create'      => 'Nová kategória',
        'file-types_header_edit'        => 'Úprava kategórie',

        'notices_title'              => 'Farské oznamy',
        'notices_description'        => 'Pridávanie rôznych oznamov v pdf súboroch',
        'notices_description_create' => 'Tu môžete pridať pdf súbor s farskými oznamami',
        'notices_description_edit'   => 'Tu môžete upraviť údaje vo farských oznamoch',
        'notices_header'             => 'Farské oznamy',
        'notices_header_create'      => 'Nový oznamy',
        'notices_header_edit'        => 'Úprava farských oznamov',

        'galleries_title'              => 'Galéria',
        'galleries_description'        => 'Obrázkové galérie na statické stránky',
        'galleries_description_create' => 'Tu môžete pridať novú obrázkovú galériu',
        'galleries_description_edit'   => 'Tu môžete upraviť údaje v galérii',
        'galleries_description_show'   => 'Detailné informácie o galérii s náhľadom',
        'galleries_header'             => 'Galérie obrázkov',
        'galleries_header_create'      => 'Nová galéria',
        'galleries_header_edit'        => 'Úprava galérie',
        'galleries_header_show'        => 'Prehliadanie galérie',

        'charts_title'              => 'Graf',
        'charts_description'        => 'Štatistiky farnosti v grafoch',
        'charts_description_create' => 'Tu môžete pridať nový graf',
        'charts_description_edit'   => 'Tu môžete upraviť graf',
        'charts_description_show'   => 'Detailné informácie o grafoch s náhľadom',
        'charts_header'             => 'Grafy',
        'charts_header_create'      => 'Nový graf',
        'charts_header_edit'        => 'Úprava grafu',
        'charts_header_show'        => 'Prehliadanie grafu',

    ]
];
